# Generated by Django 6.0 on 2025-12-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justlaw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
    ]
